[build-system]
requires = ["hatchling>=1.27"]
build-backend = "hatchling.build"


[project]
name = "lark_sqlpp"
version = "0.2"
authors = [
    { name="Dmitrii Chechetkin", email="dmitrii.chechetkin@couchbase.com" },
]
description = "A package containing lark grammar and parser method for sqlpp"
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
requires-python = ">=3.9"
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
    "lark>=1.3.1"
]

[project.urls]
Homepage = "https://github.com/couchbaselabs/sqlpp-lark"
Issues = "https://github.com/couchbaselabs/sqlpp-lark/issues"

[tool.hatch.build.targets.wheel]
packages = ["src/lark_sqlpp"]


[tool.hatch.envs.test]
extra-dependencies = [
    "mypy>=1.0.0",
]
[tool.hatch.envs.test.scripts]
check = "mypy --install-types --non-interactive {args:src/projectname tests}"
